#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Turkish -> English strings for the Digirella design system."""

T = {
# ---------- component page: section copy ----------
"Bileşenler": "Components",
"Bileşenler — Digirella": "Components — Digirella",
"34 bileşenin çalışan hâli. Buradaki her şeye tıklayabilir, klavyeyle gezebilir, durumları gerçek zamanlı görebilirsin. Kurallar ve ne zaman hangisini kullanacağın": "All 34 components, working. Click anything here, move through it with the keyboard, and watch the states change in real time. The rules and guidance on when to use each one live in the",
"referans dokümanında": "reference docs",
"referans dokümanı": "reference docs",
"Digirella tasarım sistemi · 34 bileşen · Kurallar için": "Digirella design system · 34 components · For the rules, see the",
"↳ Canlı bileşenler": "↳ Live components",

"Beş varyant, üç boyut. Üzerine gel, tıkla, Tab ile odaklan — hepsi ayrı durum.": "Five variants, three sizes. Hover, click, or focus with Tab — each is a separate state.",
"Odak halkası yalnızca klavyeyle gezerken çıkar — fareyle tıkladığında görünmez. Bu bilinçli:": "The focus ring appears only when navigating by keyboard, not on mouse click. That's deliberate:",
"kullanılıyor.": "is used.",
"Yalnızca ikon taşıyan dairesel aksiyon. Her zaman erişilebilir bir ad gerekir.": "A circular, icon-only action. It always needs an accessible name.",
"Durum işareti. Etkileşimli değil — tıklanabilir bir şey gerekiyorsa Tag kullan.": "A status marker. Not interactive — if you need something clickable, use Tag.",
"Üç yükseklik. Sonuncusu etkileşimli — üzerine geldiğinde yükselir.": "Three elevations. The last one is interactive — it lifts on hover.",
"Sayfa yüzeyine oturan varsayılan kap.": "The default container, sitting flat on the page surface.",
"Listelerde birbirinden ayrılması gereken kartlar.": "For cards in a list that need to separate from each other.",
"Üzerine gel ya da Tab ile odaklan.": "Hover over it, or focus with Tab.",
"Seçilebilir filtre çipi. Soldakiler seçimi değiştirir, sağdakiler kaldırılabilir.": "A selectable filter chip. The ones on the left toggle; the ones on the right can be removed.",
"Etiket, ipucu ve hata yuvası. Odaklandığında kenarlık yeşile döner.": "Label, hint, and error slot. The border turns green on focus.",
"Karakter sayacı yaz dedikçe güncellenir; sınıra ulaşınca kırmızıya döner.": "The character counter updates as you type and turns red at the limit.",
"Kısa ve sabit listeler için tarayıcının kendi seçim kutusu, sistemin kabuğuyla.": "The browser's own select for short, fixed lists, wearing the system's chrome.",
"Birden çok seçim. Açıklama satırı isteğe bağlı.": "Multiple selection. The description line is optional.",
"Birden yalnızca biri. Aynı": "Exactly one of many. Grouped under a shared",
"altında gruplanır.": "attribute.",
"Anında uygulanan ayar. Kaydet düğmesi gerekiyorsa Switch değil Checkbox kullan.": "A setting that applies instantly. If a save button is needed, use Checkbox instead of Switch.",
"Tek değerli aralık. Sürüklerken sayı anlık güncellenir.": "A single-value range. The number updates live as you drag.",
"Sepet adedi. Sınıra ulaşınca ilgili düğme kendini devre dışı bırakır.": "Cart quantity. The relevant button disables itself at the limit.",
"Uzun listeler için yazarak süzme. Kutuya tıkla, sonra bir şeyler yaz.": "Type-ahead filtering for long lists. Click the box, then start typing.",
"Çoklu seçim. Üçten fazlasında kalanlar": "Multiple selection. Beyond three, the rest collapse into",
"olarak toplanır.": ".",
"Menü seçim yaptıkça açık kalır — birden fazla seçmek doğal olsun diye.": "The menu stays open as you select, so picking several feels natural.",
"Hiyerarşiden tek seçim. Yalnızca yaprak düğümler seçilebilir.": "A single choice from a hierarchy. Only leaf nodes are selectable.",
"Görünüm değiştirici. Ok tuşlarıyla da gezilir.": "A view switcher. Arrow keys work too.",
"İki ile dört arası görünüm seçeneği için kompakt anahtar.": "A compact switch for two to four view options.",
"Sayfa sayısı arttıkça aradaki sayılar üç noktaya toplanır. 12. sayfaya git, listenin nasıl yeniden kurulduğunu gör.": "As the page count grows, the numbers in between collapse into an ellipsis. Jump to page 12 and watch the list rebuild.",
"Kategori izi. En fazla dört seviye; sonuncusu bulunduğun sayfadır.": "A category trail. Four levels at most; the last item is the page you're on.",
"Çok adımlı akışta ilerleme. Tamamlananlar dolu, bulunduğun adım çerçeveli.": "Progress through a multi-step flow. Completed steps are filled; the current one is outlined.",
"Başlıklara tıkla — sıralama çalışıyor. Kutucuklar tekil ve toplu seçim yapar, üsttekinin belirsiz hâli de var.": "Click the headers — sorting works. The checkboxes handle single and bulk selection, and the one in the header has an indeterminate state.",
"Aynı anda tek panel açık. Yükseklik animasyonu": "One panel open at a time. The height animates with",
"ile, sabit yükseklik tahmini yok.": ", so there's no hardcoded height to guess at.",
"Satıcı kimliği. Görsel yoksa baş harflere düşer.": "Seller identity. Falls back to initials when there's no image.",
"Belirli ilerleme. Düğmeye bas, dolum animasyonlu ilerlesin.": "Determinate progress. Press a button and watch the fill animate.",
"Üstteki salt okunur, alttaki girdi. Yıldızların üzerinde gez, önizleme görünsün.": "The top one is read-only, the bottom one is an input. Hover the stars to preview.",
"Yerini alacağı içeriğin şeklini taklit eden yükleme göstergesi.": "A loading placeholder shaped like the content that will replace it.",
"Sayfa düzeyinde kalıcı durum mesajı. Kapatma düğmesi gerçekten kaldırır.": "A persistent, page-level status message. The close button really does remove it.",
"Odak tuzağı, Escape ile kapanma, karartıya tıklayınca çıkış ve odağın tetikleyiciye dönmesi — hepsi çalışıyor. Aç ve Tab'a basmayı sürdür.": "Focus trapping, Escape to close, click-the-scrim to dismiss, and focus returning to the trigger — all of it works. Open one and keep pressing Tab.",
"Geçici bildirim. Dört saniye sonra kendi kendine kaybolur, üst üste yığılır.": "A transient notification. It clears itself after four seconds and stacks when there are several.",
"Kısa ipucu. Fareyle üzerine gel ya da Tab ile odaklan — ikisinde de çıkar.": "A short hint. Hover with the mouse or focus with Tab — it appears either way.",
"Kenardan açılan panel. Filtre ve sepet gibi sayfayı terk ettirmeyen yan işler için.": "A panel anchored to the edge. For side tasks like filters and cart that shouldn't take you off the page.",
"Tetikleyiciye bağlı aksiyon listesi. Dışarı tıklayınca ya da Escape ile kapanır.": "A list of actions attached to a trigger. Closes on outside click or Escape.",
"Menüden farkı: içine herhangi bir şey koyabilirsin, sadece aksiyon listesi değil.": "How it differs from Menu: you can put anything inside, not just a list of actions.",

# ---------- UI labels ----------
"Satın al": "Buy now", "Sepete ekle": "Add to cart", "Satıcıya yaz": "Message seller",
"Vazgeç": "Cancel", "İlanı sil": "Delete listing", "Devre dışı": "Disabled",
"Küçük": "Small", "Orta": "Medium", "Büyük": "Large",
"Favorilere ekle": "Add to favourites", "Paylaş": "Share", "Ekle": "Add", "Sil": "Delete",
"Kapat": "Close", "Kaldır": "Remove", "Düzenle": "Edit", "Kopyala": "Duplicate",
"Bağlantıyı paylaş": "Share link", "Arşivle": "Archive", "İşlemler ▾": "Actions ▾",
"Taslak": "Draft", "Yayında": "Live", "İncelemede": "In review", "Stok az": "Low stock",
"Reddedildi": "Rejected", "Öne çıkan": "Featured", "Öne çıkar": "Feature this",
"Elektronik": "Electronics", "Ev & yaşam": "Home & living", "Ev &amp; yaşam": "Home &amp; living",
"Moda": "Fashion", "Kargo bedava": "Free shipping", "500 ₺ altı": "Under ₺500",
"İlan başlığı": "Listing title", "Örn. iPhone 14 Pro 256 GB": "e.g. iPhone 14 Pro 256 GB",
"Alıcının arama yaparken yazacağı kelimeleri kullan.": "Use the words a buyer would type when searching.",
"E-posta": "Email", "Geçerli bir e-posta adresi gir.": "Enter a valid email address.",
"Satıcı kodu": "Seller code", "Kayıt sırasında atanır, değiştirilemez.": "Assigned at signup and can't be changed.",
"Ürün açıklaması": "Product description",
"Ürünün durumunu, kusurlarını ve kutu içeriğini yaz.": "Describe the condition, any flaws, and what's in the box.",
"Kargo firması": "Carrier", "Durum": "Status", "İnceleme bitene kadar kilitli.": "Locked until review finishes.",
"Yurtiçi Kargo": "Yurtiçi Kargo", "Aras Kargo": "Aras Kargo", "MNG Kargo": "MNG Kargo",
"Sürat Kargo": "Sürat Kargo", "PTT Kargo": "PTT Kargo",
"Yurtiçi": "Yurtiçi", "Aras": "Aras", "MNG": "MNG", "Sürat": "Sürat", "Elden teslim": "Local pickup",
"500 ₺ üzeri siparişlerde kargoyu sen karşılarsın.": "You cover shipping on orders over ₺500.",
"Pazarlık payı bırak": "Allow offers", "Kurumsal hesaplara açık.": "Available on business accounts.",
"Sıfır": "Brand new", "Kutusu açılmamış, hiç kullanılmamış.": "Unopened box, never used.",
"Yeni gibi": "Like new", "Birkaç kez kullanılmış, izi yok.": "Used a few times, no marks.",
"İkinci el": "Used", "Kullanım izleri var, çalışır durumda.": "Shows wear, in working order.",
"Sipariş bildirimleri": "Order notifications", "Haftalık satış özeti": "Weekly sales summary",
"Tatil modu": "Holiday mode", "Üst fiyat sınırı": "Maximum price", "Üst fiyat": "Max price",
"Üst sınır": "Upper limit", "En fazla 5 adet": "5 maximum", "Azalt": "Decrease", "Artır": "Increase",
"Kategori": "Category", "Kategori seç": "Choose a category", "Ara…": "Search…",
"Cep telefonu": "Mobile phones", "Dizüstü bilgisayar": "Laptops", "Kulaklık": "Headphones",
"Akıllı saat": "Smartwatches", "Fotoğraf makinesi": "Cameras",
"Eşleşen kategori yok": "No matching categories",
"Kargo seçenekleri": "Shipping options", "Seçim yap": "Make a selection", "Seç": "Select",
"Alt kategori": "Subcategory", "Kategori ağacı": "Category tree", "Mobilya": "Furniture", "Mutfak": "Kitchen",
"Tümü": "All", "Arşiv": "Archived",
"Hesabındaki bütün ilanlar, durumu ne olursa olsun.": "Every listing on your account, whatever its status.",
"Alıcıların şu anda görebildiği ilanlar.": "Listings buyers can see right now.",
"Henüz yayınlanmamış, üzerinde çalıştığın ilanlar.": "Listings you're still working on, not yet published.",
"Yayından kaldırdığın, kaydı tutulan ilanlar.": "Listings you've taken down, kept on record.",
"Izgara": "Grid", "Liste": "List", "Harita": "Map",
"Önceki sayfa": "Previous page", "Sonraki sayfa": "Next page", "Sayfa": "Page",
"Sayfa 1 / 24": "Page 1 of 24", "Konum": "Location", "Ana sayfa": "Home",
"Ürün bilgisi": "Product details", "Görseller": "Photos", "Fiyat": "Price", "Kargo": "Shipping",
"Ürün": "Product", "Görüntülenme": "Views", "Tümünü seç": "Select all",
"Anker güç bankası": "Anker power bank",
"Kargo ne zaman çıkar?": "When does an order ship?",
"Saat 15.00'e kadar verilen siparişler aynı gün kargoya verilir. Sonrasındakiler ertesi iş günü çıkar.": "Orders placed before 3pm ship the same day. Anything later goes out the next business day.",
"İade koşulları neler?": "What are the return terms?",
"Teslimattan sonra 14 gün içinde, kullanılmamış ve kutusu hasarsız ürünlerde koşulsuz iade hakkın var.": "You can return anything unused and in undamaged packaging within 14 days of delivery, no reason needed.",
"Fatura nasıl alırım?": "How do I get an invoice?",
"Fatura, kargo çıkışıyla birlikte hesabındaki e-posta adresine otomatik gönderilir. Siparişler sayfasından da indirebilirsin.": "The invoice is emailed to your account address as soon as the order ships. You can also download it from the Orders page.",
"Profil tamamlanma": "Profile completion",
"1 yıldız": "1 star", "2 yıldız": "2 stars", "3 yıldız": "3 stars", "4 yıldız": "4 stars", "5 yıldız": "5 stars",
"4,2 · 318 değerlendirme": "4.2 · 318 reviews", "Puan ver": "Rate this", "Girdi": "Input",
"İlan yayınlandı": "Listing published", "Ürünün artık aramalarda görünüyor.": "Your product now appears in search.",
"Kargo anlaşman 12 Eylül'de yenilenecek.": "Your shipping agreement renews on 12 September.",
"Stok azaldı": "Stock is running low", "Üç üründe stok ikinin altına düştü.": "Three products have fewer than two left.",
"Ödeme alınamadı": "Payment failed", "Kayıtlı kartın son kullanma tarihi geçmiş.": "Your saved card has expired.",
"Başarı": "Success", "Uyarı": "Warning", "Hata": "Error", "Bilgi": "Info",
"Kaydedildi": "Saved", "Değişikliklerin yayına alındı.": "Your changes are live.",
"Kopyalandı": "Copied", "İlan bağlantısı panoda.": "The listing link is on your clipboard.",
"Bu üründen 2 adet kaldı.": "Only 2 of this product left.",
"Yüklenemedi": "Upload failed", "Görsel 5 MB sınırını aşıyor.": "The image is over the 5 MB limit.",
"Komisyon oranı kategoriye göre değişir": "Commission varies by category",
"Alt": "Bottom", "Sağ": "Right", "Aşağıda açılır": "Opens below", "Sağda açılır": "Opens to the right",
"Filtreleri aç": "Open filters", "Filtreler": "Filters", "4.328 sonuç": "4,328 results",
"Yalnızca ücretsiz kargo": "Free shipping only", "Temizle": "Clear", "Sonuçları göster": "Show results",
"Filtreler uygulandı": "Filters applied", "312 sonuç bulundu.": "Found 312 results.",
"Fiyat aralığı ▾": "Price range ▾", "Uygula": "Apply",
"İlanı silmek üzeresin": "You're about to delete this listing",
"iPhone 14 Pro ilanı kalıcı olarak kaldırılacak. Bu ilana ait 1.847 görüntülenme ve 12 favori kaydı da silinir. Bu işlem geri alınamaz.": "The iPhone 14 Pro listing will be removed permanently, along with its 1,847 views and 12 saved favourites. This can't be undone.",
"Kalıcı olarak sil": "Delete permanently", "İlan silindi": "Listing deleted",
"Fiyatı düzenle": "Edit price", "Satış fiyatı": "Sale price",
"Kategori komisyonu düşüldükten sonra eline 30.132 ₺ geçer.": "After category commission you receive ₺30,132.",
"Takipçilere indirim bildirimi gönder": "Notify followers of the price drop",
"Değişiklikleri kaydet": "Save changes", "Fiyat güncellendi": "Price updated",
"Yeni fiyat aramalarda birkaç dakika içinde görünür.": "The new price appears in search within a few minutes.",
"Bilgi": "Info", "Boyutlar": "Sizes",

# ---------- storefront kit ----------
"Daha iyi al, sat": "Buy better, sell better", "Bugün öne çıkanlar": "Featured today",
"Hızlı teslimat": "Fast delivery", "Ücretsiz kargo": "Free shipping", "Ücretsiz iade": "Free returns",
"Satılan": "Sold", "Tükendi": "Out of stock", "Yeni": "New",
"Kargo bilgileri": "Shipping details", "Standart teslimat · 2–4 iş günü": "Standard delivery · 2–4 business days",
"· yarın": "· tomorrow", "İstanbul": "Istanbul", "Aydın": "Aydın", "Deniz Aydın": "Deniz Aydın",
"Bağdat Cad. 128/4": "128/4 Bağdat Cad.", "Geçerli bir posta kodu girin": "Enter a valid postcode",
"Kartı kontrol edin": "Check your card details", "Siparişi iptal et?": "Cancel this order?",
"Bu işlem geri alınamaz. Ödeme 3–5 iş gününde iade edilir.": "This can't be undone. The payment is refunded within 3–5 business days.",
"İptal et": "Cancel order", "Kampanya e-postaları": "Promotional emails",
"Satıcı tatil modu": "Seller holiday mode", "Sipariş bildirimleri buraya gider": "Order notifications go here",
"2 ürün": "2 items", "İkinci el ×": "Used ×", "NÇ": "NC",

# ---------- guidelines / tokens ----------
"Varsayılan": "Default", "varsayılan": "default", "Odaklanmış": "Focused", "Hatalı": "Error",
"Pasif · yalnız pasif durumda": "Disabled · disabled state only",
"İkincil metin · 6.9:1": "Secondary text · 6.9:1", "Yardımcı metin · 4.9:1": "Helper text · 4.9:1",
"Bağlantı · 7.2:1": "Link · 7.2:1",
"Yalnız teknik/sabit veride kullanılır — gövde metninde asla.": "For technical and fixed data only — never in body copy.",
"Body · 16/1.5 · 400. Gövde metni ölçüsü 60–75 karakteri geçmez; uzun paragraflar için --layout-content-width kullanılır.": "Body · 16/1.5 · 400. Body measure stays within 60–75 characters; use --layout-content-width for long passages.",
"hover, focus, renk geçişi": "hover, focus, colour transitions",
"açılır menü, popover": "dropdown menu, popover", "modal, sayfa geçişi": "modal, page transition",
"Kaynaklarda logo dosyası yoktu. Gerçek marka işareti geldiğinde assets/ klasörüne eklenmeli; şimdilik her yerde düz kelime işareti kullanılır.": "No logo file was supplied. When the real brand mark arrives it should go in assets/; for now a plain wordmark is used everywhere.",

# ---------- dsCard / startingPoint metadata ----------
'subtitle="Logo dosyası verilmedi — marka adı düz tipografiyle yazılır"': 'subtitle="No logo file supplied — the brand name is set in plain type"',
'subtitle="Odak halkası her zaman primary yeşil"': 'subtitle="The focus ring is always primary green"',
'subtitle="Süreler ve easing eğrileri"': 'subtitle="Durations and easing curves"',
'subtitle="Hafif yeşile çalan nötr ölçek"': 'subtitle="A neutral scale with a slight green cast"',
'subtitle="Yeşil primary ölçeği — 60 ana marka rengidir (#006A09)"': 'subtitle="The green primary scale — 60 is the core brand colour (#006A09)"',
'subtitle="Primary rengin izinli kullanımları"': 'subtitle="Approved uses of the primary colour"',
'subtitle="Metin renk tokenleri ve kontrast notları"': 'subtitle="Text colour tokens and contrast notes"',
'subtitle="Tabs — aktif sekme yeşil alt çizgi"': 'subtitle="Tabs — the active tab gets a green underline"',
'subtitle="Köşe yarıçapları · xs → pill"': 'subtitle="Corner radii · xs → pill"',
'subtitle="4px tabanlı ölçek · space-0 → space-13"': 'subtitle="A 4px-based scale · space-0 → space-13"',
'subtitle="Gölge katmanları · 100 → 400"': 'subtitle="Shadow layers · 100 → 400"',
'subtitle="Kart içi ritim: 20px padding, 12px iç boşluk"': 'subtitle="Rhythm inside a card: 20px padding, 12px inner gap"',
'subtitle="Ana sayfa, ürün ve ödeme akışı"': 'subtitle="Home, product, and checkout flow"',
'subtitle="IBM Plex Mono — kod, SKU, sipariş numarası"': 'subtitle="IBM Plex Mono — code, SKUs, order numbers"',
'subtitle="1.200 minor third ölçeği, 11→56px"': 'subtitle="A 1.200 minor-third scale, 11→56px"',
'subtitle="Public Sans · display ve title rolleri"': 'subtitle="Public Sans · display and title roles"',
'subtitle="Pazaryeri vitrini — arama, ürün, ödeme"': 'subtitle="Marketplace storefront — search, product, checkout"',
'subtitle="Buton varyantları ve boyutları"': 'subtitle="Button variants and sizes"',
'subtitle="Yüzey kabı — flat, raised, floating"': 'subtitle="Surface container — flat, raised, floating"',
'subtitle="Aranabilir seçim alanı"': 'subtitle="Searchable select field"',
'subtitle="Etiketli metin alanı"': 'subtitle="Labelled text field"',
'subtitle="Çoklu seçim"': 'subtitle="Multiple selection"',
'subtitle="Hiyerarşik seçim"': 'subtitle="Hierarchical selection"',
'subtitle="Görünüm değiştirici"': 'subtitle="View switcher"',
'subtitle="Kenardan açılan panel"': 'subtitle="Edge-anchored panel"',
'subtitle="Veri tablosu"': 'subtitle="Data table"',
'subtitle="Modal diyalog"': 'subtitle="Modal dialog"',
'subtitle="Sayfalama"': 'subtitle="Pagination"',

# ---------- runtime strings in interactive.js ----------
'"Önceki sayfa"': '"Previous page"',
'"Sonraki sayfa"': '"Next page"',
"`Sayfa ${n} / ${count}`": "`Page ${n} of ${count}`",
'"Kapat"': '"Close"',
'"Seç"': '"Select"',
"seçildi": "selected",
}

# Strings that must never be substring-replaced (too short / ambiguous).
EXACT_ONLY = {"Fiyat","Kargo","Ürün","Durum","Ekle","Sil","Kapat","Seç","Yeni","Tümü","Sayfa",
              "Sağ","Alt","Aras","MNG","Sürat","Yurtiçi","Moda","Bilgi","Hata","Uyarı","Başarı",
              "Girdi","Liste","Harita","Izgara","Küçük","Orta","Büyük","Kategori","E-posta",
              "Varsayılan","varsayılan","Odaklanmış","Hatalı","Taslak","Yayında","Boyutlar",
              "Kopyala","Düzenle","Paylaş","Kaldır","Uygula","Temizle","Filtreler","Konum"}
